<?php
/**
 * Data1
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Antera Api v1
 *
 * Antera API v1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Data1 Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Data1 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Data1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
'product_id' => 'string',
'product_name' => 'string',
'description' => 'string',
'vendor_name' => 'string',
'vendor_id' => 'string',
'inhouse_id' => 'string',
'item_code' => 'string',
'antera_id' => 'string',
'production_time' => 'string',
'package' => 'string',
'additional_info' => 'string',
'coop' => 'string',
'rebate' => 'string',
'tax_enabled' => 'bool',
'price' => 'string',
'special_price' => 'string',
'qb_expense_account' => 'string',
'qb_income_account' => 'string',
'qb_asset_account' => 'string',
'imprint_info' => 'string',
'po_type' => 'string',
'clone_id' => 'string',
'assigned_user_id' => 'string',
'assigned_user_name' => 'string',
'product_category_array' => 'string[]',
'store_array' => 'string[]',
'product_part_array' => '\Swagger\Client\Model\ProductPartArray1',
'media_content' => '\Swagger\Client\Model\MediaContent[]',
'product_type' => 'string',
'product_type_name' => 'string',
'fob_points' => '\Swagger\Client\Model\FobPoint[]',
'shell' => 'bool'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
'product_id' => null,
'product_name' => null,
'description' => null,
'vendor_name' => null,
'vendor_id' => null,
'inhouse_id' => null,
'item_code' => null,
'antera_id' => null,
'production_time' => null,
'package' => null,
'additional_info' => null,
'coop' => null,
'rebate' => null,
'tax_enabled' => null,
'price' => null,
'special_price' => null,
'qb_expense_account' => null,
'qb_income_account' => null,
'qb_asset_account' => null,
'imprint_info' => null,
'po_type' => null,
'clone_id' => null,
'assigned_user_id' => null,
'assigned_user_name' => null,
'product_category_array' => null,
'store_array' => null,
'product_part_array' => null,
'media_content' => null,
'product_type' => null,
'product_type_name' => null,
'fob_points' => null,
'shell' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'product_id' => 'productId',
'product_name' => 'productName',
'description' => 'description',
'vendor_name' => 'vendorName',
'vendor_id' => 'vendorId',
'inhouse_id' => 'inhouseId',
'item_code' => 'itemCode',
'antera_id' => 'anteraId',
'production_time' => 'productionTime',
'package' => 'package',
'additional_info' => 'additionalInfo',
'coop' => 'coop',
'rebate' => 'rebate',
'tax_enabled' => 'taxEnabled',
'price' => 'price',
'special_price' => 'specialPrice',
'qb_expense_account' => 'qbExpenseAccount',
'qb_income_account' => 'qbIncomeAccount',
'qb_asset_account' => 'qbAssetAccount',
'imprint_info' => 'imprintInfo',
'po_type' => 'poType',
'clone_id' => 'cloneId',
'assigned_user_id' => 'assignedUserId',
'assigned_user_name' => 'assignedUserName',
'product_category_array' => 'ProductCategoryArray',
'store_array' => 'StoreArray',
'product_part_array' => 'ProductPartArray',
'media_content' => 'MediaContent',
'product_type' => 'productType',
'product_type_name' => 'productTypeName',
'fob_points' => 'fobPoints',
'shell' => 'shell'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'product_id' => 'setProductId',
'product_name' => 'setProductName',
'description' => 'setDescription',
'vendor_name' => 'setVendorName',
'vendor_id' => 'setVendorId',
'inhouse_id' => 'setInhouseId',
'item_code' => 'setItemCode',
'antera_id' => 'setAnteraId',
'production_time' => 'setProductionTime',
'package' => 'setPackage',
'additional_info' => 'setAdditionalInfo',
'coop' => 'setCoop',
'rebate' => 'setRebate',
'tax_enabled' => 'setTaxEnabled',
'price' => 'setPrice',
'special_price' => 'setSpecialPrice',
'qb_expense_account' => 'setQbExpenseAccount',
'qb_income_account' => 'setQbIncomeAccount',
'qb_asset_account' => 'setQbAssetAccount',
'imprint_info' => 'setImprintInfo',
'po_type' => 'setPoType',
'clone_id' => 'setCloneId',
'assigned_user_id' => 'setAssignedUserId',
'assigned_user_name' => 'setAssignedUserName',
'product_category_array' => 'setProductCategoryArray',
'store_array' => 'setStoreArray',
'product_part_array' => 'setProductPartArray',
'media_content' => 'setMediaContent',
'product_type' => 'setProductType',
'product_type_name' => 'setProductTypeName',
'fob_points' => 'setFobPoints',
'shell' => 'setShell'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'product_id' => 'getProductId',
'product_name' => 'getProductName',
'description' => 'getDescription',
'vendor_name' => 'getVendorName',
'vendor_id' => 'getVendorId',
'inhouse_id' => 'getInhouseId',
'item_code' => 'getItemCode',
'antera_id' => 'getAnteraId',
'production_time' => 'getProductionTime',
'package' => 'getPackage',
'additional_info' => 'getAdditionalInfo',
'coop' => 'getCoop',
'rebate' => 'getRebate',
'tax_enabled' => 'getTaxEnabled',
'price' => 'getPrice',
'special_price' => 'getSpecialPrice',
'qb_expense_account' => 'getQbExpenseAccount',
'qb_income_account' => 'getQbIncomeAccount',
'qb_asset_account' => 'getQbAssetAccount',
'imprint_info' => 'getImprintInfo',
'po_type' => 'getPoType',
'clone_id' => 'getCloneId',
'assigned_user_id' => 'getAssignedUserId',
'assigned_user_name' => 'getAssignedUserName',
'product_category_array' => 'getProductCategoryArray',
'store_array' => 'getStoreArray',
'product_part_array' => 'getProductPartArray',
'media_content' => 'getMediaContent',
'product_type' => 'getProductType',
'product_type_name' => 'getProductTypeName',
'fob_points' => 'getFobPoints',
'shell' => 'getShell'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['product_id'] = isset($data['product_id']) ? $data['product_id'] : null;
        $this->container['product_name'] = isset($data['product_name']) ? $data['product_name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['vendor_name'] = isset($data['vendor_name']) ? $data['vendor_name'] : null;
        $this->container['vendor_id'] = isset($data['vendor_id']) ? $data['vendor_id'] : null;
        $this->container['inhouse_id'] = isset($data['inhouse_id']) ? $data['inhouse_id'] : null;
        $this->container['item_code'] = isset($data['item_code']) ? $data['item_code'] : null;
        $this->container['antera_id'] = isset($data['antera_id']) ? $data['antera_id'] : null;
        $this->container['production_time'] = isset($data['production_time']) ? $data['production_time'] : null;
        $this->container['package'] = isset($data['package']) ? $data['package'] : null;
        $this->container['additional_info'] = isset($data['additional_info']) ? $data['additional_info'] : null;
        $this->container['coop'] = isset($data['coop']) ? $data['coop'] : null;
        $this->container['rebate'] = isset($data['rebate']) ? $data['rebate'] : null;
        $this->container['tax_enabled'] = isset($data['tax_enabled']) ? $data['tax_enabled'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['special_price'] = isset($data['special_price']) ? $data['special_price'] : null;
        $this->container['qb_expense_account'] = isset($data['qb_expense_account']) ? $data['qb_expense_account'] : null;
        $this->container['qb_income_account'] = isset($data['qb_income_account']) ? $data['qb_income_account'] : null;
        $this->container['qb_asset_account'] = isset($data['qb_asset_account']) ? $data['qb_asset_account'] : null;
        $this->container['imprint_info'] = isset($data['imprint_info']) ? $data['imprint_info'] : null;
        $this->container['po_type'] = isset($data['po_type']) ? $data['po_type'] : null;
        $this->container['clone_id'] = isset($data['clone_id']) ? $data['clone_id'] : null;
        $this->container['assigned_user_id'] = isset($data['assigned_user_id']) ? $data['assigned_user_id'] : null;
        $this->container['assigned_user_name'] = isset($data['assigned_user_name']) ? $data['assigned_user_name'] : null;
        $this->container['product_category_array'] = isset($data['product_category_array']) ? $data['product_category_array'] : null;
        $this->container['store_array'] = isset($data['store_array']) ? $data['store_array'] : null;
        $this->container['product_part_array'] = isset($data['product_part_array']) ? $data['product_part_array'] : null;
        $this->container['media_content'] = isset($data['media_content']) ? $data['media_content'] : null;
        $this->container['product_type'] = isset($data['product_type']) ? $data['product_type'] : null;
        $this->container['product_type_name'] = isset($data['product_type_name']) ? $data['product_type_name'] : null;
        $this->container['fob_points'] = isset($data['fob_points']) ? $data['fob_points'] : null;
        $this->container['shell'] = isset($data['shell']) ? $data['shell'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['product_id'] === null) {
            $invalidProperties[] = "'product_id' can't be null";
        }
        if ($this->container['product_name'] === null) {
            $invalidProperties[] = "'product_name' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['vendor_name'] === null) {
            $invalidProperties[] = "'vendor_name' can't be null";
        }
        if ($this->container['vendor_id'] === null) {
            $invalidProperties[] = "'vendor_id' can't be null";
        }
        if ($this->container['inhouse_id'] === null) {
            $invalidProperties[] = "'inhouse_id' can't be null";
        }
        if ($this->container['item_code'] === null) {
            $invalidProperties[] = "'item_code' can't be null";
        }
        if ($this->container['antera_id'] === null) {
            $invalidProperties[] = "'antera_id' can't be null";
        }
        if ($this->container['production_time'] === null) {
            $invalidProperties[] = "'production_time' can't be null";
        }
        if ($this->container['package'] === null) {
            $invalidProperties[] = "'package' can't be null";
        }
        if ($this->container['additional_info'] === null) {
            $invalidProperties[] = "'additional_info' can't be null";
        }
        if ($this->container['coop'] === null) {
            $invalidProperties[] = "'coop' can't be null";
        }
        if ($this->container['rebate'] === null) {
            $invalidProperties[] = "'rebate' can't be null";
        }
        if ($this->container['tax_enabled'] === null) {
            $invalidProperties[] = "'tax_enabled' can't be null";
        }
        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        if ($this->container['special_price'] === null) {
            $invalidProperties[] = "'special_price' can't be null";
        }
        if ($this->container['qb_expense_account'] === null) {
            $invalidProperties[] = "'qb_expense_account' can't be null";
        }
        if ($this->container['qb_income_account'] === null) {
            $invalidProperties[] = "'qb_income_account' can't be null";
        }
        if ($this->container['qb_asset_account'] === null) {
            $invalidProperties[] = "'qb_asset_account' can't be null";
        }
        if ($this->container['imprint_info'] === null) {
            $invalidProperties[] = "'imprint_info' can't be null";
        }
        if ($this->container['po_type'] === null) {
            $invalidProperties[] = "'po_type' can't be null";
        }
        if ($this->container['clone_id'] === null) {
            $invalidProperties[] = "'clone_id' can't be null";
        }
        if ($this->container['assigned_user_id'] === null) {
            $invalidProperties[] = "'assigned_user_id' can't be null";
        }
        if ($this->container['assigned_user_name'] === null) {
            $invalidProperties[] = "'assigned_user_name' can't be null";
        }
        if ($this->container['product_category_array'] === null) {
            $invalidProperties[] = "'product_category_array' can't be null";
        }
        if ($this->container['store_array'] === null) {
            $invalidProperties[] = "'store_array' can't be null";
        }
        if ($this->container['product_part_array'] === null) {
            $invalidProperties[] = "'product_part_array' can't be null";
        }
        if ($this->container['media_content'] === null) {
            $invalidProperties[] = "'media_content' can't be null";
        }
        if ($this->container['product_type'] === null) {
            $invalidProperties[] = "'product_type' can't be null";
        }
        if ($this->container['product_type_name'] === null) {
            $invalidProperties[] = "'product_type_name' can't be null";
        }
        if ($this->container['fob_points'] === null) {
            $invalidProperties[] = "'fob_points' can't be null";
        }
        if ($this->container['shell'] === null) {
            $invalidProperties[] = "'shell' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return string
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string $product_id product_id
     *
     * @return $this
     */
    public function setProductId($product_id)
    {
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets product_name
     *
     * @return string
     */
    public function getProductName()
    {
        return $this->container['product_name'];
    }

    /**
     * Sets product_name
     *
     * @param string $product_name product_name
     *
     * @return $this
     */
    public function setProductName($product_name)
    {
        $this->container['product_name'] = $product_name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets vendor_name
     *
     * @return string
     */
    public function getVendorName()
    {
        return $this->container['vendor_name'];
    }

    /**
     * Sets vendor_name
     *
     * @param string $vendor_name vendor_name
     *
     * @return $this
     */
    public function setVendorName($vendor_name)
    {
        $this->container['vendor_name'] = $vendor_name;

        return $this;
    }

    /**
     * Gets vendor_id
     *
     * @return string
     */
    public function getVendorId()
    {
        return $this->container['vendor_id'];
    }

    /**
     * Sets vendor_id
     *
     * @param string $vendor_id vendor_id
     *
     * @return $this
     */
    public function setVendorId($vendor_id)
    {
        $this->container['vendor_id'] = $vendor_id;

        return $this;
    }

    /**
     * Gets inhouse_id
     *
     * @return string
     */
    public function getInhouseId()
    {
        return $this->container['inhouse_id'];
    }

    /**
     * Sets inhouse_id
     *
     * @param string $inhouse_id inhouse_id
     *
     * @return $this
     */
    public function setInhouseId($inhouse_id)
    {
        $this->container['inhouse_id'] = $inhouse_id;

        return $this;
    }

    /**
     * Gets item_code
     *
     * @return string
     */
    public function getItemCode()
    {
        return $this->container['item_code'];
    }

    /**
     * Sets item_code
     *
     * @param string $item_code item_code
     *
     * @return $this
     */
    public function setItemCode($item_code)
    {
        $this->container['item_code'] = $item_code;

        return $this;
    }

    /**
     * Gets antera_id
     *
     * @return string
     */
    public function getAnteraId()
    {
        return $this->container['antera_id'];
    }

    /**
     * Sets antera_id
     *
     * @param string $antera_id antera_id
     *
     * @return $this
     */
    public function setAnteraId($antera_id)
    {
        $this->container['antera_id'] = $antera_id;

        return $this;
    }

    /**
     * Gets production_time
     *
     * @return string
     */
    public function getProductionTime()
    {
        return $this->container['production_time'];
    }

    /**
     * Sets production_time
     *
     * @param string $production_time production_time
     *
     * @return $this
     */
    public function setProductionTime($production_time)
    {
        $this->container['production_time'] = $production_time;

        return $this;
    }

    /**
     * Gets package
     *
     * @return string
     */
    public function getPackage()
    {
        return $this->container['package'];
    }

    /**
     * Sets package
     *
     * @param string $package package
     *
     * @return $this
     */
    public function setPackage($package)
    {
        $this->container['package'] = $package;

        return $this;
    }

    /**
     * Gets additional_info
     *
     * @return string
     */
    public function getAdditionalInfo()
    {
        return $this->container['additional_info'];
    }

    /**
     * Sets additional_info
     *
     * @param string $additional_info additional_info
     *
     * @return $this
     */
    public function setAdditionalInfo($additional_info)
    {
        $this->container['additional_info'] = $additional_info;

        return $this;
    }

    /**
     * Gets coop
     *
     * @return string
     */
    public function getCoop()
    {
        return $this->container['coop'];
    }

    /**
     * Sets coop
     *
     * @param string $coop coop
     *
     * @return $this
     */
    public function setCoop($coop)
    {
        $this->container['coop'] = $coop;

        return $this;
    }

    /**
     * Gets rebate
     *
     * @return string
     */
    public function getRebate()
    {
        return $this->container['rebate'];
    }

    /**
     * Sets rebate
     *
     * @param string $rebate rebate
     *
     * @return $this
     */
    public function setRebate($rebate)
    {
        $this->container['rebate'] = $rebate;

        return $this;
    }

    /**
     * Gets tax_enabled
     *
     * @return bool
     */
    public function getTaxEnabled()
    {
        return $this->container['tax_enabled'];
    }

    /**
     * Sets tax_enabled
     *
     * @param bool $tax_enabled tax_enabled
     *
     * @return $this
     */
    public function setTaxEnabled($tax_enabled)
    {
        $this->container['tax_enabled'] = $tax_enabled;

        return $this;
    }

    /**
     * Gets price
     *
     * @return string
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param string $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets special_price
     *
     * @return string
     */
    public function getSpecialPrice()
    {
        return $this->container['special_price'];
    }

    /**
     * Sets special_price
     *
     * @param string $special_price special_price
     *
     * @return $this
     */
    public function setSpecialPrice($special_price)
    {
        $this->container['special_price'] = $special_price;

        return $this;
    }

    /**
     * Gets qb_expense_account
     *
     * @return string
     */
    public function getQbExpenseAccount()
    {
        return $this->container['qb_expense_account'];
    }

    /**
     * Sets qb_expense_account
     *
     * @param string $qb_expense_account qb_expense_account
     *
     * @return $this
     */
    public function setQbExpenseAccount($qb_expense_account)
    {
        $this->container['qb_expense_account'] = $qb_expense_account;

        return $this;
    }

    /**
     * Gets qb_income_account
     *
     * @return string
     */
    public function getQbIncomeAccount()
    {
        return $this->container['qb_income_account'];
    }

    /**
     * Sets qb_income_account
     *
     * @param string $qb_income_account qb_income_account
     *
     * @return $this
     */
    public function setQbIncomeAccount($qb_income_account)
    {
        $this->container['qb_income_account'] = $qb_income_account;

        return $this;
    }

    /**
     * Gets qb_asset_account
     *
     * @return string
     */
    public function getQbAssetAccount()
    {
        return $this->container['qb_asset_account'];
    }

    /**
     * Sets qb_asset_account
     *
     * @param string $qb_asset_account qb_asset_account
     *
     * @return $this
     */
    public function setQbAssetAccount($qb_asset_account)
    {
        $this->container['qb_asset_account'] = $qb_asset_account;

        return $this;
    }

    /**
     * Gets imprint_info
     *
     * @return string
     */
    public function getImprintInfo()
    {
        return $this->container['imprint_info'];
    }

    /**
     * Sets imprint_info
     *
     * @param string $imprint_info imprint_info
     *
     * @return $this
     */
    public function setImprintInfo($imprint_info)
    {
        $this->container['imprint_info'] = $imprint_info;

        return $this;
    }

    /**
     * Gets po_type
     *
     * @return string
     */
    public function getPoType()
    {
        return $this->container['po_type'];
    }

    /**
     * Sets po_type
     *
     * @param string $po_type po_type
     *
     * @return $this
     */
    public function setPoType($po_type)
    {
        $this->container['po_type'] = $po_type;

        return $this;
    }

    /**
     * Gets clone_id
     *
     * @return string
     */
    public function getCloneId()
    {
        return $this->container['clone_id'];
    }

    /**
     * Sets clone_id
     *
     * @param string $clone_id clone_id
     *
     * @return $this
     */
    public function setCloneId($clone_id)
    {
        $this->container['clone_id'] = $clone_id;

        return $this;
    }

    /**
     * Gets assigned_user_id
     *
     * @return string
     */
    public function getAssignedUserId()
    {
        return $this->container['assigned_user_id'];
    }

    /**
     * Sets assigned_user_id
     *
     * @param string $assigned_user_id assigned_user_id
     *
     * @return $this
     */
    public function setAssignedUserId($assigned_user_id)
    {
        $this->container['assigned_user_id'] = $assigned_user_id;

        return $this;
    }

    /**
     * Gets assigned_user_name
     *
     * @return string
     */
    public function getAssignedUserName()
    {
        return $this->container['assigned_user_name'];
    }

    /**
     * Sets assigned_user_name
     *
     * @param string $assigned_user_name assigned_user_name
     *
     * @return $this
     */
    public function setAssignedUserName($assigned_user_name)
    {
        $this->container['assigned_user_name'] = $assigned_user_name;

        return $this;
    }

    /**
     * Gets product_category_array
     *
     * @return string[]
     */
    public function getProductCategoryArray()
    {
        return $this->container['product_category_array'];
    }

    /**
     * Sets product_category_array
     *
     * @param string[] $product_category_array product_category_array
     *
     * @return $this
     */
    public function setProductCategoryArray($product_category_array)
    {
        $this->container['product_category_array'] = $product_category_array;

        return $this;
    }

    /**
     * Gets store_array
     *
     * @return string[]
     */
    public function getStoreArray()
    {
        return $this->container['store_array'];
    }

    /**
     * Sets store_array
     *
     * @param string[] $store_array store_array
     *
     * @return $this
     */
    public function setStoreArray($store_array)
    {
        $this->container['store_array'] = $store_array;

        return $this;
    }

    /**
     * Gets product_part_array
     *
     * @return \Swagger\Client\Model\ProductPartArray1
     */
    public function getProductPartArray()
    {
        return $this->container['product_part_array'];
    }

    /**
     * Sets product_part_array
     *
     * @param \Swagger\Client\Model\ProductPartArray1 $product_part_array product_part_array
     *
     * @return $this
     */
    public function setProductPartArray($product_part_array)
    {
        $this->container['product_part_array'] = $product_part_array;

        return $this;
    }

    /**
     * Gets media_content
     *
     * @return \Swagger\Client\Model\MediaContent[]
     */
    public function getMediaContent()
    {
        return $this->container['media_content'];
    }

    /**
     * Sets media_content
     *
     * @param \Swagger\Client\Model\MediaContent[] $media_content media_content
     *
     * @return $this
     */
    public function setMediaContent($media_content)
    {
        $this->container['media_content'] = $media_content;

        return $this;
    }

    /**
     * Gets product_type
     *
     * @return string
     */
    public function getProductType()
    {
        return $this->container['product_type'];
    }

    /**
     * Sets product_type
     *
     * @param string $product_type product_type
     *
     * @return $this
     */
    public function setProductType($product_type)
    {
        $this->container['product_type'] = $product_type;

        return $this;
    }

    /**
     * Gets product_type_name
     *
     * @return string
     */
    public function getProductTypeName()
    {
        return $this->container['product_type_name'];
    }

    /**
     * Sets product_type_name
     *
     * @param string $product_type_name product_type_name
     *
     * @return $this
     */
    public function setProductTypeName($product_type_name)
    {
        $this->container['product_type_name'] = $product_type_name;

        return $this;
    }

    /**
     * Gets fob_points
     *
     * @return \Swagger\Client\Model\FobPoint[]
     */
    public function getFobPoints()
    {
        return $this->container['fob_points'];
    }

    /**
     * Sets fob_points
     *
     * @param \Swagger\Client\Model\FobPoint[] $fob_points fob_points
     *
     * @return $this
     */
    public function setFobPoints($fob_points)
    {
        $this->container['fob_points'] = $fob_points;

        return $this;
    }

    /**
     * Gets shell
     *
     * @return bool
     */
    public function getShell()
    {
        return $this->container['shell'];
    }

    /**
     * Sets shell
     *
     * @param bool $shell shell
     *
     * @return $this
     */
    public function setShell($shell)
    {
        $this->container['shell'] = $shell;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
