<?php
/**
 * CreatecontactRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Antera Api v1
 *
 * Antera API v1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreatecontactRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreatecontactRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreatecontactRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreatecontactRequest"
     */
    public function testCreatecontactRequest()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
    }

    /**
     * Test attribute "reports_to"
     */
    public function testPropertyReportsTo()
    {
    }

    /**
     * Test attribute "commission_group"
     */
    public function testPropertyCommissionGroup()
    {
    }

    /**
     * Test attribute "shipping_info"
     */
    public function testPropertyShippingInfo()
    {
    }

    /**
     * Test attribute "sales_rep"
     */
    public function testPropertySalesRep()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "lead_source"
     */
    public function testPropertyLeadSource()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "billing"
     */
    public function testPropertyBilling()
    {
    }

    /**
     * Test attribute "shipping"
     */
    public function testPropertyShipping()
    {
    }
}
