<?php
/**
 * Design2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Antera Api v1
 *
 * Antera API v1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Design2Test Class Doc Comment
 *
 * @category    Class
 * @description Design2
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Design2Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Design2"
     */
    public function testDesign2()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "is_master"
     */
    public function testPropertyIsMaster()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "date_modified"
     */
    public function testPropertyDateModified()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "design_type"
     */
    public function testPropertyDesignType()
    {
    }

    /**
     * Test attribute "design_form_type"
     */
    public function testPropertyDesignFormType()
    {
    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {
    }

    /**
     * Test attribute "customer_name"
     */
    public function testPropertyCustomerName()
    {
    }

    /**
     * Test attribute "deco_vendor_id"
     */
    public function testPropertyDecoVendorId()
    {
    }

    /**
     * Test attribute "deco_vendor_name"
     */
    public function testPropertyDecoVendorName()
    {
    }

    /**
     * Test attribute "deco_vendor_no"
     */
    public function testPropertyDecoVendorNo()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "type_files"
     */
    public function testPropertyTypeFiles()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "stitch_count"
     */
    public function testPropertyStitchCount()
    {
    }

    /**
     * Test attribute "deco_detail_count_name"
     */
    public function testPropertyDecoDetailCountName()
    {
    }

    /**
     * Test attribute "saved_to_disk"
     */
    public function testPropertySavedToDisk()
    {
    }

    /**
     * Test attribute "variation"
     */
    public function testPropertyVariation()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "design_description_stitches"
     */
    public function testPropertyDesignDescriptionStitches()
    {
    }

    /**
     * Test attribute "color_thread"
     */
    public function testPropertyColorThread()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "order_numbers"
     */
    public function testPropertyOrderNumbers()
    {
    }

    /**
     * Test attribute "related_orders"
     */
    public function testPropertyRelatedOrders()
    {
    }

    /**
     * Test attribute "design_images"
     */
    public function testPropertyDesignImages()
    {
    }
}
