<?php
/**
 * Variation2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Antera Api v1
 *
 * Antera API v1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Variation2Test Class Doc Comment
 *
 * @category    Class
 * @description Variation2
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Variation2Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Variation2"
     */
    public function testVariation2()
    {
    }

    /**
     * Test attribute "design_variation_unique_id"
     */
    public function testPropertyDesignVariationUniqueId()
    {
    }

    /**
     * Test attribute "item_image"
     */
    public function testPropertyItemImage()
    {
    }

    /**
     * Test attribute "item_image_thumbnail"
     */
    public function testPropertyItemImageThumbnail()
    {
    }

    /**
     * Test attribute "design_variation_product"
     */
    public function testPropertyDesignVariationProduct()
    {
    }

    /**
     * Test attribute "design_variation_color"
     */
    public function testPropertyDesignVariationColor()
    {
    }

    /**
     * Test attribute "design_variation_location"
     */
    public function testPropertyDesignVariationLocation()
    {
    }

    /**
     * Test attribute "design_note"
     */
    public function testPropertyDesignNote()
    {
    }

    /**
     * Test attribute "design_color_thread_pms"
     */
    public function testPropertyDesignColorThreadPms()
    {
    }
}
