<?php
/**
 * ArtworkApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Antera Api v1
 *
 * Antera API v1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ArtworkApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ArtworkApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createArtwork
     *
     * Create artwork.
     *
     */
    public function testCreateArtwork()
    {
    }

    /**
     * Test case for deleteArtwork
     *
     * Delete artwork.
     *
     */
    public function testDeleteArtwork()
    {
    }

    /**
     * Test case for getArtworkDetails
     *
     * Get artwork details.
     *
     */
    public function testGetArtworkDetails()
    {
    }

    /**
     * Test case for listArtwork
     *
     * List artwork.
     *
     */
    public function testListArtwork()
    {
    }

    /**
     * Test case for listAvailableArtworkStatuses
     *
     * List available artwork statuses.
     *
     */
    public function testListAvailableArtworkStatuses()
    {
    }

    /**
     * Test case for updateArtwork
     *
     * Update artwork.
     *
     */
    public function testUpdateArtwork()
    {
    }
}
