<?php
/**
 * OrdersItemRowsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Antera Api v1
 *
 * Antera API v1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * OrdersItemRowsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrdersItemRowsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrderItemRow
     *
     * Create order item row.
     *
     */
    public function testCreateOrderItemRow()
    {
    }

    /**
     * Test case for deleteOrderItemRow
     *
     * Delete order item row.
     *
     */
    public function testDeleteOrderItemRow()
    {
    }

    /**
     * Test case for getOrderItemRowDetails
     *
     * Get order item row details.
     *
     */
    public function testGetOrderItemRowDetails()
    {
    }

    /**
     * Test case for listOrderItemRows
     *
     * List order item rows.
     *
     */
    public function testListOrderItemRows()
    {
    }

    /**
     * Test case for updateOrderItemRow
     *
     * Update order item row.
     *
     */
    public function testUpdateOrderItemRow()
    {
    }
}
