<?php
/**
 * OrderItemDecorationDetailsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Antera Api v1
 *
 * Antera API v1
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * OrderItemDecorationDetailsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderItemDecorationDetailsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrderItemDecorationDetails
     *
     * Create order item decoration details.
     *
     */
    public function testCreateOrderItemDecorationDetails()
    {
    }

    /**
     * Test case for deleteOrderItemDecorationDetails
     *
     * Delete order item decoration details.
     *
     */
    public function testDeleteOrderItemDecorationDetails()
    {
    }

    /**
     * Test case for getOrderItemDecorationDetails1
     *
     * Get order item decoration details.
     *
     */
    public function testGetOrderItemDecorationDetails1()
    {
    }

    /**
     * Test case for listOrderItemDecorationDetails
     *
     * List order item decoration details.
     *
     */
    public function testListOrderItemDecorationDetails()
    {
    }

    /**
     * Test case for updateOrderItemDecorationDetails
     *
     * Update order item decoration details.
     *
     */
    public function testUpdateOrderItemDecorationDetails()
    {
    }
}
